name: SSL Certificate Monitor

on:
  schedule:
    - cron: '0 9 * * 1' # Runs every Monday at 09:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  check-ssl:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSL certificate
        run: |
          DOMAIN="chrisjones.org.uk"
          EXPIRY_DATE=$(echo | openssl s_client -connect $DOMAIN:443 -servername $DOMAIN 2>/dev/null \
          | openssl x509 -noout -enddate | cut -d= -f2)
          
          EXPIRY_SECONDS=$(date -d "$EXPIRY_DATE" +%s)
          NOW_SECONDS=$(date +%s)
          DAYS_LEFT=$(( ($EXPIRY_SECONDS - $NOW_SECONDS) / 86400 ))

          echo "Certificate for $DOMAIN expires in $DAYS_LEFT days"

          if [ $DAYS_LEFT -lt 20 ]; then
            echo "::error ::SSL certificate expires in less than 20 days!"
            exit 1
          fi

